{% set name = "periodictable" %}
{% set version = "1.7.1" %}
{% set sha256 = "43d7db7233d6b33962f83d79ea54f47c3b923d3e83403cbc03f58f353af4b52c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - numpy
    - pyparsing

test:
  imports:
    - periodictable
    - periodictable.density

about:
  home: http://www.reflectometry.org/danse/elements.html
  license: Public domain
  summary: 'Extensible periodic table for python'

  description: |
    The periodictable package provides an extensible periodic table
    of the elements prepopulated with data important to neutron and
    X-ray scattering experiments. With the elements pacakge you can
    compute the scattering potential of a compound at a given wavelength.
  doc_url: http://www.reflectometry.org/danse/docs/elements/
  dev_url: https://github.com/pkienzle/periodictable

extra:
  recipe-maintainers:
    - bjodah
    - mrakitin
