{% set name = "periodictable" %}
{% set version = "1.6.1" %}
{% set sha256 = "7c501c9f73d77b1fb28cb51e85b28429c2c44a99ce3d1274894564c72d712603" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - pyparsing

test:
  imports:
    - periodictable
    - periodictable.density

about:
  home: http://www.reflectometry.org/danse/elements.html
  license: Public domain
  summary: Extensible periodic table for python

  description: |
    The periodictable package provides an extensible periodic table
    of the elements prepopulated with data important to neutron and
    X-ray scattering experiments. With the elements pacakge you can
    compute the scattering potential of a compound at a given wavelength.
  doc_url: http://www.reflectometry.org/danse/docs/elements/
  dev_url: https://github.com/pkienzle/periodictable

extra:
  recipe-maintainers:
    - bjodah
