travis:
  secure:
    BINSTAR_TOKEN: cqoae4NYk/Ti4AixCFhRB49azAbJO/a6h84A7A6xnJQSGec2sCuGgeqWDITTD4o6yXwXPCDE30v6Kxh9k5WDROV+kbgFrodyjDoQs6l3Q6BbTKFAF6crJuJ7nb5tFcLK3BC/wzy9+OTuJiUdYhR5bDhQwgbe6F7Qf05YGvJWxkflRQJ3lpTJl6gSbYIWLPcIeUiW4hZkSQG668g1Mg/GPz3EHEt6LrdmeGwKxMHVHx0Cs+3CbLF8D4doaeiwDwSPQ27lRwX6gT9eBh1YHo/z2lBmfZcxdXZeprL2Nu1dOJ4lJzU/y0iaS8nKME6+rHA5gYzvw5sL1A2m0zAAPCjkmu1UJ+UhrRiJH03QgcsTP0gcTGfGMtQRjNFYoyQL8TjPoSBysueTIjWNQrsPaehvlq3a4RpOCFUh6vE4WtqOL0TWLVEUDVHz64MxF+HVT/4mJtX7+1IlGVNEwvV3mFrFxVm9aYTVtLh2a6B9WriD+rHwYqj1ydAEl0TqUr5uDEX8TTckSM9G+f/dg6plKt72VxPFCkkGbwbLhsSfP0Bun0YYZCZNvjml0x0vKqhxH5ZQtYjMivOwr1T3Ufc7xxg5y4EAy6lu5dSjsMd4EaHAmnakuFyFTXL8nRlAqcBJiYt5bYh+mOH3JtoWC8nIZJ+7RkI0paqcwYkiDOkN8/Phxzs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
